
import torch

bart = torch.hub.load('pytorch/fairseq', 'bart.large.cnn')
bart.cuda()
bart.eval()
import time

slines = [ "'I gave him everything, I don’t want anything, I don’t need anything for anything,' Trump said. 'She calls me up: ‘It’s the nicest thing that’s ever happened. Thank you so much. John would be so thrilled. He’s looking down. He’d be so thrilled. Thank you so much, sir.’ I said, ‘That’s OK, don’t worry about it.' 'Maybe he’s looking up, I don’t know,' Trump added, to laughs and groans. 'I don’t know. Maybe, but let’s assume he’s looking down.” The White House at first told reporters to ask the president about his comments, but then justified them as a normal political attack and suggested he’d gotten caught up in the moment."]

slines = ["Once upon a time there was a dear little girl who was loved by every one who looked at her, but most of all by her grandmother, and there was nothing that she would not have given to the child. Once she gave her a little cap of red velvet, which suited her so well that she would never wear anything else. So she was always called Little Red Riding Hood. One day her mother said to her, ‘Come, Little Red Riding Hood, here is a piece of cake and a bottle of wine. Take them to your grandmother, she is ill and weak, and they will do her good. Set out before it gets hot, and when you are going, walk nicely and quietly and do not run off the path, or you may fall and break the bottle, and then your grandmother will get nothing. And when you go into her room, don't forget to say, good-morning, and don't peep into every corner before you do it.’ I will take great care, said Little Red Riding Hood to her mother, and gave her hand on it. The grandmother lived out in the wood, half a league from the village, and just as Little Red Riding Hood entered the wood, a wolf met her. Little Red Riding Hood did not know what a wicked creature he was, and was not at all afraid of him. ‘Good-day, Little Red Riding Hood,’ said he. ‘Thank you kindly, wolf.’ ‘Whither away so early, Little Red Riding Hood?’ ‘To my grandmother's.’ ‘What have you got in your apron?’ ‘Cake and wine. Yesterday was baking-day, so poor sick grandmother is to have something good, to make her stronger.’ ‘Where does your grandmother live, Little Red Riding Hood?’"]

slines = ["part from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count, simply place your cursor into the text box above and start typing. You'll see the number of characters and words increase or decrease as you type, delete, and edit them. You can also copy and paste text from another program over into the online editor above. The Auto-Save feature will make sure you won't lose any changes while editing, even if you leave the site and come back later. Tip: Bookmark this page now."]
# ttt = bart.encode(slines[0])
slines = ["I had forgotten that I ordered this book, and was surprised and delighted when it arrived today, albeit in a package from Goodwill. Having read the first three volumes of His Dark Materials with great pleasure, I was happy to learn more about their history in this entertaining prequel. Here the author tells us of the history of the great bear, Iorek Byrnison, and the aeronaut, Lee Scoresby. In this case they are fighting for the little guy, like super-heroes. Despite the gun-play, there is some delicious ironic humor to lighten things up. I do not hesitate to recommend this book partly because it moves along nicely and because it is beautifully written. I meant to mention the small art work on many pages and on the game--inside the back cover--John Lawrence's handsome engravings. There are also two letters written by Lyra later surnamed Silvertongue, the heroine of the first volumes, as she proceeds through the final phase of graduate school. It sounds as though she will use he experiences as the basis for a dissertation in Economic History."]
slines = ["Cassie McDowell’s life in 1980s Minnesota seems perfectly wholesome. She lives on a farm, loves school, and has a crush on the nicest boy in class. Yes, there are her parents’ strange parties and their parade of deviant guests, but she’s grown accustomed to them. All that changes when someone comes hunting in Lilydale. One by one, local boys go missing. One by one, they return changed—violent, moody, and withdrawn. What happened to them becomes the stuff of shocking rumors. The accusations of who’s responsible grow just as wild, and dangerous town secrets start to surface. Then Cassie’s own sister undergoes the dark change. If she is to survive, Cassie must find her way in an adult world where every sin is justified, and only the truth is unforgivable."]
# print(len(ttt))
for i in range(10):
    i += 1
    start = time.time()
    slines = ["White House press secretary Stephanie Grisham defended President Donald Trump’s attack on Rep. Debbie Dingell (D-MI), who’s grieving the death of her husband. The Michigan Democrat voted to impeach the president, who complained to rally goers Wednesday night that he had ordered flags flown at half mast to honor the late Rep. John Dingell — and suggested the veteran lawmaker might be in hell. I gave him everything, I don’t want anything, I don’t need anything for anything,” Trump said. “She calls me up: ‘It’s the nicest thing that’s ever happened. Thank you so much. John would be so thrilled. He’s looking down. He’d be so thrilled. Thank you so much, sir.’ I said, ‘That’s OK, don’t worry about it.’"]
    slines = slines * i
    hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
    #hypotheses_batch = bart.sample(slines, beam=4, lenpen=1.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
    end = start - time.time()
    print(hypotheses_batch)
    print(f"{i} repitions in time:")
    print(end)